version: "3.7"
 
services: 
  flask:
    build: ./flaska
    container_name: mshswaggerflask
    image: mshswaggerflask:0.1.0
    restart: always
    environment:
      - APP_NAME=FlaskApp
    #expose:
    #    - 8200
    ports:    
       - "8200:8200"
  nginx:
    build: ./nginxd
    container_name: mshswaggernginx
    image: mshswaggernginx:1.0.0
    restart: always
    ports:
      - "8250:8250"
    depends_on:
      - flask
      
  #db:
    #image: postgres
    #container_name: postgres
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_DB: db_name
    #  POSTGRES_USER: postgres_n
    #  POSTGRES_PASSWORD: postgres_p
    #ports:
    #  - 5432:5432